apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bonanza-index
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 7600
    targetPort: 7600
    nodePort: 30076
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    nodePort: 30191
    protocol: TCP
    name: questdb
  - port: 9001
    targetPort: 9001
    nodePort: 30192
    protocol: TCP
    name: minio-console
  - port: 9002
    targetPort: 9002
    nodePort: 30193
    protocol: TCP
    name: minio-api
  selector:
    app: nginx

