apiVersion: v1
kind: Service
metadata:
  name: index-calculator
  namespace: bonanza-index
  labels:
    app: index-calculator
spec:
  type: NodePort
  ports:
  - port: 10201
    targetPort: 10201
    nodePort: 31021
    protocol: TCP
    name: http
  - port: 6757
    targetPort: 6757
    protocol: TCP
    name: zmq-pub
  selector:
    app: index-calculator

