apiVersion: v1
kind: Service
metadata:
  name: orderbook-collector
  namespace: bonanza-index
  labels:
    app: orderbook-collector
spec:
  type: ClusterIP
  ports:
  - port: 6001
    targetPort: 6001
    protocol: TCP
    name: http
  selector:
    app: orderbook-collector

