#!/bin/bash

# k3s-agent 포트 충돌 해결 스크립트

echo "🔧 k3s-agent 포트 충돌 해결"
echo "================================"
echo ""

echo "⚠️  워커 노드에서 실행해야 합니다"
echo ""
echo "문제: listen tcp 127.0.0.1:6444: bind: address already in use"
echo "원인: 포트 6444가 이미 사용 중이거나 이전 k3s 프로세스가 실행 중"
echo ""
echo "해결 방법:"
echo "================================"
echo ""
echo "1. 실행 중인 k3s 프로세스 확인:"
echo "   ps aux | grep k3s | grep -v grep"
echo ""
echo "2. k3s 프로세스 종료:"
echo "   sudo /usr/local/bin/k3s-killall.sh"
echo ""
echo "3. 포트 6444를 사용하는 프로세스 확인:"
echo "   sudo lsof -i :6444"
echo "   # 또는"
echo "   sudo netstat -tlnp | grep 6444"
echo ""
echo "4. 프로세스 종료 (필요한 경우):"
echo "   sudo kill -9 <PID>"
echo ""
echo "5. k3s-agent 재시작:"
echo "   sudo systemctl restart k3s-agent"
echo ""
echo "6. 상태 확인:"
echo "   sudo systemctl status k3s-agent"
echo ""
echo "================================"
echo "또는 완전 재시작:"
echo "================================"
echo ""
echo "1. k3s-agent 완전 종료:"
echo "   sudo systemctl stop k3s-agent"
echo "   sudo /usr/local/bin/k3s-killall.sh"
echo ""
echo "2. 잠시 대기:"
echo "   sleep 5"
echo ""
echo "3. k3s-agent 재시작:"
echo "   sudo systemctl start k3s-agent"
echo ""
echo "4. 로그 확인:"
echo "   sudo journalctl -u k3s-agent -f"
echo ""

