#!/bin/bash

# 워커 노드 k3s-agent 수정 스크립트

echo "🔧 워커 노드 k3s-agent 수정"
echo "================================"
echo ""

echo "⚠️  워커 노드에서 실행해야 합니다"
echo ""
echo "문제: node IP \"121.88.4.57\" not found"
echo "원인: WSL2에서는 공인 IP가 네트워크 인터페이스에 직접 할당되지 않음"
echo ""
echo "해결 방법:"
echo "================================"
echo ""
echo "1. k3s-agent 서비스 중지:"
echo "   sudo systemctl stop k3s-agent"
echo ""
echo "2. k3s-agent 환경 변수 파일 확인/수정:"
echo "   sudo cat /etc/systemd/system/k3s-agent.service.env"
echo ""
echo "   K3S_NODE_IP가 설정되어 있다면 제거:"
echo "   sudo sed -i '/K3S_NODE_IP/d' /etc/systemd/system/k3s-agent.service.env"
echo ""
echo "3. k3s-agent 재시작:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl start k3s-agent"
echo ""
echo "4. 상태 확인:"
echo "   sudo systemctl status k3s-agent"
echo "   kubectl get nodes -o wide"
echo ""
echo "================================"
echo "또는 k3s-agent 재설치:"
echo "================================"
echo ""
echo "1. k3s-agent 제거:"
echo "   sudo systemctl stop k3s-agent"
echo "   sudo /usr/local/bin/k3s-agent-uninstall.sh"
echo ""
echo "2. 재설치 (노드 IP 자동 감지):"
echo "   export K3S_TOKEN=<토큰>"
echo "   export K3S_URL=https://121.88.4.53:6443"
echo "   curl -sfL https://get.k3s.io | K3S_TOKEN=\$K3S_TOKEN K3S_URL=\$K3S_URL INSTALL_K3S_EXEC=\"--with-node-id --node-name bonanza-worker\" sh -"
echo ""
echo "   💡 --node-ip 옵션을 제거하면 자동으로 네트워크 인터페이스 IP를 감지합니다"
echo ""

