#!/bin/bash

# 워커 노드 IP 설정 수정 스크립트

echo "🔧 워커 노드 IP 설정 수정"
echo "================================"
echo ""

WORKER_NODE="bonanza-worker"
PUBLIC_IP="121.88.4.57"

echo "워커 노드: $WORKER_NODE"
echo "설정할 공인 IP: $PUBLIC_IP"
echo ""

echo "⚠️  주의: 이 작업은 워커 노드에서 직접 실행해야 합니다"
echo ""
echo "워커 노드에서 실행할 명령어:"
echo "================================"
echo ""
echo "1. k3s-agent 서비스 중지:"
echo "   sudo systemctl stop k3s-agent"
echo ""
echo "2. k3s-agent 환경 변수 파일 수정:"
echo "   sudo nano /etc/systemd/system/k3s-agent.service.env"
echo ""
echo "   또는 다음 내용 추가/수정:"
echo "   sudo bash -c 'echo \"K3S_NODE_IP=$PUBLIC_IP\" >> /etc/systemd/system/k3s-agent.service.env'"
echo ""
echo "3. k3s-agent 환경 변수 파일 확인:"
echo "   cat /etc/systemd/system/k3s-agent.service.env"
echo ""
echo "4. k3s-agent 재시작:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl start k3s-agent"
echo ""
echo "5. 노드 주소 확인:"
echo "   kubectl get node $WORKER_NODE -o jsonpath='{.status.addresses}' | jq"
echo ""
echo "================================"
echo "또는 k3s 재설치 (노드 IP 지정):"
echo "================================"
echo ""
echo "1. k3s-agent 제거:"
echo "   sudo /usr/local/bin/k3s-agent-uninstall.sh"
echo ""
echo "2. 노드 IP 지정하여 재설치 (내부 IP 사용, 외부 IP는 별도 지정):"
echo "   export K3S_TOKEN=<토큰>"
echo "   export K3S_URL=https://121.88.4.53:6443"
echo "   # WSL2에서는 내부 IP를 사용하고, 외부 IP는 node-external-ip로 지정"
echo "   curl -sfL https://get.k3s.io | K3S_TOKEN=\$K3S_TOKEN K3S_URL=\$K3S_URL INSTALL_K3S_EXEC=\"--with-node-id --node-name bonanza-worker --node-external-ip $PUBLIC_IP\" sh -"
echo ""
echo "   또는 내부 IP를 자동 감지하도록 (권장):"
echo "   curl -sfL https://get.k3s.io | K3S_TOKEN=\$K3S_TOKEN K3S_URL=\$K3S_URL INSTALL_K3S_EXEC=\"--with-node-id --node-name bonanza-worker\" sh -"
echo ""
echo "================================"
echo "현재 노드 주소 확인:"
echo "================================"
kubectl get node "$WORKER_NODE" -o jsonpath='{.status.addresses[*]}' | tr ' ' '\n' | grep -E "InternalIP|ExternalIP" || echo "   노드 정보 확인 실패"
echo ""

