apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  poolname: "bonanza"  # ZFS 풀 이름
allowedTopologies:
  - matchLabelExpressions:
    - key: kubernetes.io/hostname
      values:
      - ubuntu  # 노드 이름 (kubectl get nodes로 확인)

